version: "3.7"

services:
  postgres:
    image: postgres:11.8
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - ./modules/service/src/main/resources/db/migration:/docker-entrypoint-initdb.d/
